# https://taskfile.dev

version: '3'

vars:
  HELM_CHART: https://github.com/marvell/universal-chart/releases/download/v0.1.0/universal-chart-0.1.0.tgz
  HELM_RELEASE: running-calc-0

tasks:
  run:
    cmds:
      - open ./index.html

  install:
    cmds:
      - helm upgrade --install --atomic {{ .HELM_RELEASE }} {{ .HELM_CHART }} -f ./.cicd/deploy/values.yaml

  uninstall:
    cmds:
      - helm uninstall --wait {{ .HELM_RELEASE }}