name: Build and Deploy

on:
  push:
    branches: ["main"]

jobs:
  docker-build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: registry.ndr.su
          username: ${{ secrets.DR0_LOGIN }}
          password: ${{ secrets.DR0_PASSWORD }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ vars.DOCKER_IMAGE }}

      - uses: docker/build-push-action@v6
        id: push
        with:
          context: .
          file: ./.cicd/build/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  release:
    needs: docker-build-and-publish
    if: success()

    runs-on: ubuntu-latest
    steps:
      - uses: azure/setup-helm@v4.2.0
      - uses: arduino/setup-task@v2

      - name: Set up KUBECONFIG
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Install
        run: task install