name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: docker/login-action@v3
        with:
          registry: registry.ndr.su
          username: ${{ secrets.DR0_LOGIN }}
          password: ${{ secrets.DR0_PASSWORD }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: registry.ndr.su/marvell/running-calc

      - uses: docker/build-push-action@v6
        id: push
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
